apiVersion: v1
kind: Service
metadata:
  name: mlops-service
  namespace: mlops
  labels:
    app: mlops-app
spec:
  type: NodePort
  selector:
    app: mlops-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
